"""Add real-time bidding features

Revision ID: 43ff737da16d
Revises: d088ae17bb4b
Create Date: 2025-07-18 16:31:37.239745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ff737da16d'
down_revision = 'd088ae17bb4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum type for BidStatus
    bidstatus_enum = sa.Enum('ACTIVE', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', name='bidstatus')
    bidstatus_enum.create(op.get_bind())
    
    op.create_table('auction_rooms',
    sa.Column('commodity_listing_id', sa.UUID(), nullable=False),
    sa.Column('current_highest_bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_highest_bidder_id', sa.UUID(), nullable=True),
    sa.Column('total_bids', sa.Integer(), nullable=True),
    sa.Column('active_participants', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pkid', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commodity_listing_id'], ['commodity_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_highest_bidder_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('commodity_listing_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_auction_rooms_active', 'auction_rooms', ['is_active'], unique=False)
    op.create_index('idx_auction_rooms_bids', 'auction_rooms', ['total_bids'], unique=False)
    op.add_column('bids', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('bids', sa.Column('status', bidstatus_enum, nullable=False, server_default='ACTIVE'))
    op.add_column('bids', sa.Column('bid_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('bids', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('unique_user_commodity_listing_bids', 'bids', type_='unique')
    op.drop_constraint('unique_user_listing_bids', 'bids', type_='unique')
    op.create_index('idx_bids_bid_time', 'bids', ['bid_time'], unique=False)
    op.create_index('idx_bids_commodity_status', 'bids', ['commodity_listing_id', 'status'], unique=False)
    op.create_index('idx_bids_user_status', 'bids', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bids_user_status', table_name='bids')
    op.drop_index('idx_bids_commodity_status', table_name='bids')
    op.drop_index('idx_bids_bid_time', table_name='bids')
    op.create_unique_constraint('unique_user_listing_bids', 'bids', ['user_id', 'listing_id'])
    op.create_unique_constraint('unique_user_commodity_listing_bids', 'bids', ['user_id', 'commodity_listing_id'])
    op.drop_column('bids', 'expires_at')
    op.drop_column('bids', 'bid_time')
    op.drop_column('bids', 'status')
    op.drop_column('bids', 'message')
    op.drop_index('idx_auction_rooms_bids', table_name='auction_rooms')
    op.drop_index('idx_auction_rooms_active', table_name='auction_rooms')
    op.drop_table('auction_rooms')
    
    # Drop enum type
    sa.Enum(name='bidstatus').drop(op.get_bind())
    # ### end Alembic commands ###
