"""fix_user_enum

Revision ID: 7a048fc82f7b
Revises: 43ff737da16d
Create Date: 2025-07-18 16:57:25.303091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a048fc82f7b'
down_revision = '43ff737da16d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
